//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanaCompetencia.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_indicador
    {
        public int id { get; set; }
        public string protocolo { get; set; }
        public int cod_drogueria { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
        public decimal valor { get; set; }
    
        public virtual Drogueria Drogueria { get; set; }
    }
}
